### PR TITLE
Fix getRecentBlockhash response destructuring

### PR DESCRIPTION
**Pull request by CriesofCarrots**

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
@jackcmay , this rpc change is part of solana v0.22.3. So I think doesn't need to be cherry-picked into the v0.22 branch here until it's bumped to v0.22.3, right?

**Comment by jackcmay** [comment]
Yes except the "stable" testnet (not to be confused with localnet) is being bumped to the latest v0.22 so the heroku app will be broken

**Comment by CriesofCarrots** [comment]
> Yes except the "stable" testnet (not to be confused with localnet) is being bumped to the latest v0.22 so the heroku app will be broken

Yes, it looks like it already is broken.
Is the fix to bump the v0.22 TTT branch to 0.22.3 and also bump travis.yml to deploy the v0.22 TTT branch to heroku?

**Comment by jackcmay** [comment]
Yes and v0.22 TTT should already be the one deployed to heroku via
.travis.yml

**Comment by CriesofCarrots** [comment]
> Yes and v0.22 TTT should already be the one deployed to heroku via .travis.yml

Oh, I see. The master branch travis.yml still says deploy 0.21. It's not affecting anything, but I'll update just so it's a little more clear.

**Comment by CriesofCarrots** [comment]
> Or we could take deploy stuff out of the master branches .travis.yml to make it even clearer that master is not being deployed

Good call. I like that better.

**Pull request merged**
