### PR TITLE
Add localnet:update to nom scripts

### PR DESCRIPTION
**Pull request by jackcmay**
Using beta by default

### CODE REVIEW

**Comment by mvines** [comment]
hmm, not sure we want to bake in beta here.  The current code uses whatever the default is in solana-web3.js, which seems nicer -- one default for all

**Comment by jackcmay** [comment]
Edge is not working for me, maybe default should be beta?

`[2019-07-03T22:49:35.571968793Z INFO  solana_bpf_loader_api::helpers] info!: "Invalid player x keep_alive"`

**Comment by mvines** [comment]
Maybe something is broken on edge, if so we should fix it instead of hiding on beta no?

**Comment by jackcmay** [comment]
Absolutely, and I suspect that edge is more unstable than beta and we want folks to have a good out of the box experience

**Comment by mvines** [comment]
More eyes on edge means we find bugs there faster :)

I don't see a strong reason to make this change.  I hear edge is broken today, let's figure out what's actually broken.  It's better we feel the pain early, it sucks to be debugging on a release branch.

**Pull request merged**
